export const filterInputItem = ['В нескольких цветах', 'Визуализация', 'Фавикон', 'Высокое разрешение', 'Исходники'];

export const linkPrice = [
  { link: 'https://kwork.ru/categories/logo/logotipy?price=_500', price: '500' },
  { link: 'https://kwork.ru/categories/logo/logotipy?price=1000_3500', price: '1 000 руб. - 3 500 руб.' },
  { link: 'https://kwork.ru/categories/logo/logotipy?price=4000_27000', price: '4000 - 27000' },
  { link: 'https://kwork.ru/categories/logo/logotipy?price=30000_', price: 'от 30 000 и выше' },
];

export const levelSalesman = [
  { link: 'https://kwork.ru/categories/logo/logotipy?sellerlvl=1', level: 'Восходящая звезда и выше' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sellerlvl=2', level: 'Высший рейтинг и выше' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sellerlvl=3', level: ' Высший рейтинг плюс' },
];

export const sellerActivity = [
  { link: 'https://kwork.ru/categories/logo/logotipy?sonline=online', level: 'Онлайн' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sonline=1', level: 'Заходил до 1 дн. назад' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sonline=3', level: 'Заходил до 3 дн. назад' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sonline=7', level: 'Заходил до 1 нед. назад' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sonline=14', level: 'Заходил до 2 нед. назад' },
];

export const positiveReviews = [
  { link: 'https://kwork.ru/categories/logo/logotipy?sminreview=1', level: 'От 1' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sminreview=5', level: 'От 5' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sminreview=20', level: 'От 20' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sminreview=100', level: 'От 100' },
];

export const deadline = [
  { link: 'https://kwork.ru/categories/logo/logotipy?sdeliverytime=1', level: 'За 24 часа' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sdeliverytime=2', level: 'До 2 дней' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sdeliverytime=3', level: 'До 3 дней' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sdeliverytime=5', level: 'До 5 дней' },
  { link: 'https://kwork.ru/categories/logo/logotipy?sdeliverytime=10', level: 'До 10 дней' },
];

export const tags = [
  { link: 'https://kwork.ru/land/logotip-dlya-kompanii', level: 'Логотип для компании' },
  { link: 'https://kwork.ru/land/logotip-dlya-sayta', level: 'Логотип для сайта' },
  { link: 'https://kwork.ru/land/logo-dlya-sayta', level: 'Лого для компании' },
  { link: 'https://kwork.ru/land/narisovat-logotip', level: 'Нарисовать логотип' },
  { link: 'https://kwork.ru/land/logo-dlya-biznesa', level: 'Лого для бизнеса' },
  { link: 'https://kwork.ru/land/firmenniy-znak', level: 'Фирменный знак' },
  { link: 'https://kwork.ru/land/kachestvenniy-logotip', level: 'Качественный логотип' },
  { link: 'https://kwork.ru/land/razrabotka-emblemy', level: 'Разработка эмблемы' },
  { link: 'https://kwork.ru/land/sozdat-logotip', level: 'Создать логотип' },
  { link: 'https://kwork.ru/land/razrabotka-logotipa', level: 'Разработка логотипа' },
  { link: 'https://kwork.ru/land/unikalniy-logotip', level: 'Уникальный логотип' },
  { link: 'https://kwork.ru/land/sozdat-dizayn-logotipa', level: 'Создать дизайн логотипа' },
  { link: 'https://kwork.ru/land/razrabotka-dizayna-logotipa', level: 'Разработка дизайна логотипа' },
  { link: 'https://kwork.ru/land/individualniy-logotip', level: 'Индивидуальный логотип' },
  { link: 'https://kwork.ru/land/kreativniy-logotip', level: 'Креативный логотип' },
  { link: 'https://kwork.ru/land/professionalniy-logotip', level: 'Профессиональный логотип' },
  { link: 'https://kwork.ru/land/vektorniy-logotip', level: 'Векторный логотип' },
  { link: 'https://kwork.ru/land/stilniy-logotip', level: 'Стильный логотип' },
  { link: 'https://kwork.ru/land/vektorniy-logo', level: 'Векторный лого' },
  { link: 'https://kwork.ru/land/sdelat-logotip', level: 'Сделать логотип' },
  { link: 'https://kwork.ru/land/iskhodnik-logotipa', level: 'Исходник логотипа' },
  { link: 'https://kwork.ru/land/dizayn-logo', level: 'Дизайн лого' },
  { link: 'https://kwork.ru/land/narisovat-dizayn-logotipa', level: 'Нарисовать дизайн логотипа' },
  { link: 'https://kwork.ru/land/originalniy-logotip', level: 'Оригинальный логотип' },
  { link: 'https://kwork.ru/land/3d-logotip', level: '3D логотип' },
  { link: 'https://kwork.ru/land/eskiz-logotipa', level: 'Эскиз логотипа' },
  { link: 'https://kwork.ru/land/logotip-dlya-biznesa', level: 'Логотип для бизнеса' },
  { link: 'https://kwork.ru/land/logotip-po-eskizu', level: 'Логотип по эскизу' },
  { link: 'https://kwork.ru/land/logo', level: 'Лого' },
  { link: 'https://kwork.ru/land/otrisovka-logotipa', level: 'Отрисовка логотипа' },
  { link: 'https://kwork.ru/land/razrabotka-logo', level: 'Разработка лого' },
  { link: 'https://kwork.ru/land/narisovat-logo', level: 'Нарисовать лого' },
  { link: 'https://kwork.ru/land/sdelat-logo', level: 'Сделать лого' },
  { link: 'https://kwork.ru/land/sozdat-logo', level: 'Создать лого' },
  { link: 'https://kwork.ru/land/vizitnaya-kartochka', level: 'Визитная карточка' },
  { link: 'https://kwork.ru/land/dizayn-vizitok', level: 'Дизайн визиток' },
  { link: 'https://kwork.ru/land/maket-vizitki', level: 'Макет визитки' },
  { link: 'https://kwork.ru/land/vizitka-dlya-biznesa', level: 'Визитка для бизнеса' },
  { link: 'https://kwork.ru/land/vizitnie-karty', level: 'Визитные карты' },
  { link: 'https://kwork.ru/land/dvustoronnyaya-vizitka', level: 'Двусторонняя визитка' },
  { link: 'https://kwork.ru/land/dizayn-vizitnoy-kartochki', level: 'Дизайн визитной карточки' },
  { link: 'https://kwork.ru/land/dizayn-maket-vizitki', level: 'Дизайн-макет визитки' },
  { link: 'https://kwork.ru/land/izgotovit-vizitku', level: 'Изготовить визитку' },
  { link: 'https://kwork.ru/land/originalniy-dizayn-vizitki', level: 'Оригинальный дизайн визитки' },
  { link: 'https://kwork.ru/land/razrabotat-dizayn-vizitki', level: 'Разработать дизайн визитки' },
  { link: 'https://kwork.ru/land/razrabotat-vizitnuyu-kartochku', level: 'Разработать визитную карточку' },
  { link: 'https://kwork.ru/land/razrabotat-maket-vizitki', level: 'Разработать макет визитки' },
  { link: 'https://kwork.ru/land/eksklyuzivnaya-vizitka', level: 'Эксклюзивная визитка' },
  { link: 'https://kwork.ru/land/sdelat-vizitku', level: 'Сделать визитку' },
  { link: 'https://kwork.ru/land/sdelat-dizayn-vizitki', level: 'Сделать дизайн визитки' },
  { link: 'https://kwork.ru/land/sdelat-maket-vizitki', level: 'Сделать макет визитки' },
  { link: 'https://kwork.ru/land/sozdat-vizitku', level: 'Создать визитку' },
  { link: 'https://kwork.ru/land/sozdat-maket-vizitki', level: 'Создать макет визитки' },
  { link: 'https://kwork.ru/land/unikalnaya-vizitka', level: 'Уникальная визитка' },
  { link: 'https://kwork.ru/land/psd-vizitki', level: 'PSD визитки' },
  { link: 'https://kwork.ru/land/narisovat-vizitku', level: 'Нарисовать визитку' },
  { link: 'https://kwork.ru/land/razrabotat-vizitku', level: 'Разработать визитку' },
  { link: 'https://kwork.ru/land/maket-poligrafii', level: 'Макет полиграфии' },
  { link: 'https://kwork.ru/land/maket-pechati', level: 'Макет печати' },
  { link: 'https://kwork.ru/land/logotip-akvarelyu', level: 'Логотип акварелью' },
  { link: 'https://kwork.ru/land/razrabotat-dizayn-firmennogo-blanka', level: 'Разработать дизайн фирменного бланка' },
  { link: 'https://kwork.ru/land/razrabotka-firmennogo-logotipa', level: 'Разработка фирменного логотипа' },
  { link: 'https://kwork.ru/land/sozdanie-firmennogo-stilya', level: 'Создание фирменного стиля' },
  { link: 'https://kwork.ru/land/razrabotka-brendbuka', level: 'Разработка брендбука' },
  { link: 'https://kwork.ru/land/sozdanie-firmennogo-blanka', level: 'Создание фирменного бланка' },
  { link: 'https://kwork.ru/land/sozdat-firmenniy-blank-s-logotipom', level: 'Создать фирменный бланк с логотипом' },
  { link: 'https://kwork.ru/land/razrabotka-firmennogo-stilya', level: 'Разработка фирменного стиля' },
  { link: 'https://kwork.ru/land/razrabotat-dizayn-blanka', level: 'Разработать дизайн бланка' },
  { link: 'https://kwork.ru/land/razrabotka-brenda', level: 'Разработка бренда' },
  { link: 'https://kwork.ru/land/razrabotka-firmennogo-blanka', level: 'Разработка фирменного бланка' },
];